Map<String, String> v = {
  'Fa' : 'Flutter app',
  'Ho' : 'ホーム',
  'Gr' : 'グラフ',
  'Ra' : 'レート',
  'Ch' : 'チャット',
  'Li' : 'ログイン',
  'Lo' : 'ログアウト',
  'Ua' : 'ユーザーアカウント',
  'Bh' : 'ホームに戻る',
  'Iu' : 'ユーザー名を入力してください',
  'Ip' : 'パスワードを入力してください',
  'Sa' : '販売所',
  'Ex' : '取引所',
  'Cr' : '暗号資産FX',
  'Fo' : '外国為替FX',
  'GMOApiRoute' : 'https://api.coin.z.com/public/v1/ticker?symbol=',
  'st' : 'status',
  'da' : 'data',
  're' : 'responsetime',
  'co' : 'GMO coin data',
};
