Map<String, String> v = {
  'Fa' : 'Flutter app',
  'Ho' : 'ホーム',
  'Gr' : 'グラフ',
  'Ra' : 'レート',
  'Ch' : 'チャット',
  'Li' : 'ログイン',
  'Lo' : 'ログアウト',
  'Ua' : 'ユーザーアカウント',
  'Bh' : 'ホームに戻る',
  'Iu' : 'ユーザー名を入力してください',
  'Ip' : 'パスワードを入力してください',
  'ExAc' : '取引所 現物',
  'ExLe' : '取引所 レバ',
  'Sa' : '販売所',
  'CrFX' : '暗号資産FX',
  'Cr' : '暗号資産',
  'FoFX' : '外国為替FX',
  'BTC' : 'https://api.coin.z.com/public/v1/ticker?symbol=BTC',
  'ETH' : 'https://api.coin.z.com/public/v1/ticker?symbol=ETH',
  'BCH' : 'https://api.coin.z.com/public/v1/ticker?symbol=BCH',
  'LTC' : 'https://api.coin.z.com/public/v1/ticker?symbol=LTC',
  'XRP' : 'https://api.coin.z.com/public/v1/ticker?symbol=XRP',
  'BTC_JPY' : 'https://api.coin.z.com/public/v1/ticker?symbol=BTC_JPY',
  'ETH_JPY' : 'https://api.coin.z.com/public/v1/ticker?symbol=ETH_JPY',
  'BCH_JPY' : 'https://api.coin.z.com/public/v1/ticker?symbol=BCH_JPY',
  'LTC_JPY' : 'https://api.coin.z.com/public/v1/ticker?symbol=LTC_JPY',
  'XRP_JPY' : 'https://api.coin.z.com/public/v1/ticker?symbol=XRP_JPY',
  'st' : 'status',
  'da' : 'data',
  're' : 'responsetime',
  'co' : 'GMO coin data',
  'Ca' : 'アカウント作成',
  'An' : 'アカウント名',
  'Ma' : 'メールアドレス',
  'Pa' : 'パスワード',
  'Pc' : 'パスワード(確認用)',
  'Fi' : '完了',
  'Cm' : 'アカウントを作成しました',
};
